name: Docs
on:
  push:
    tags:
      - v*.*.*
  workflow_dispatch:
permissions:
  contents: write
jobs:
  docs:
    runs-on: ubuntu-20.04
    steps:
      - name: Prepare
        run: |
          mkdir -p ${{github.workspace}}/src  
          mkdir -p ${{github.workspace}}/devel

      - uses: docker/setup-buildx-action@v3

      - name: Checkout
        uses: actions/checkout@v4
        with:
          path: src
          submodules: true

      - name: Build Docker Image
        uses: docker/build-push-action@v5
        with:
          tags: ros_gazebo_gym:noetic
          file: .ci/Dockerfile.noetic
          push: false
          load: true
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Compile ROS package with Catkin Tools
        uses: addnab/docker-run-action@v3
        with:
          image: ros_gazebo_gym:noetic
          options: -v ${{github.workspace}}/src:/src/ -v ${{github.workspace}}/devel:/devel/
          run: |
            rosdep install --from-paths /src --ignore-src --rosdistro noetic -y --simulate  # Check if all dependencies were in the Docker File.
            apt-get update
            rosdep install --from-paths /src --ignore-src --rosdistro noetic -y
            catkin config --init --extend /opt/ros/noetic
            catkin build --interleave-output --verbose

      - name: Build the ROS package documentation
        uses: addnab/docker-run-action@v3
        with:
          image: ros_gazebo_gym:noetic
          shell: bash
          options: -v ${{github.workspace}}/src:/src/ -v ${{github.workspace}}/devel:/devel/
          run: |
            . /devel/setup.bash
            pip install -r ../src/requirements/doc_requirements.txt
            rosdoc_lite ../src -o ../src/docs/build

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          publish_branch: gh-pages
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: src/docs/build/html
          force_orphan: true
