# Github action that updates the code version tags, adds a changelog and drafts a release when
# a new version tag is added.
name: ros-gazebo-gym release CI
on:
  push:
    tags:
      - v*.*.*
jobs:
  on-noetic-branch-check:
    runs-on: ubuntu-latest
    outputs:
      on_noetic_devel: ${{ steps.contains_tag.outputs.retval }}
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: rickstaa/action-contains-tag@v1
        id: contains_tag
        with:
          reference: "noetic"
          tag: "${{ github.ref }}"
  update-code-version:
    runs-on: ubuntu-latest
    needs: on-noetic-branch-check
    if: ${{ needs.on-noetic-branch-check.outputs.on_noetic_devel == 'true' }}
    steps:
      # NOTE: Makes sure that the version in the code files are up to date.
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          ref: ${{ github.ref }}
          fetch-depth: 0
      - name: Get current semver tag
        id: get_semver
        uses: rickstaa/action-get-semver@v1
        with:
          verbose: "true"
      # Use standard-version to update version in code
      # See. https://github.com/conventional-changelog/standard-version
      - uses: actions/setup-node@v2
        with:
          node-version: "12"
      - name: Install pnpm
        run: |
          npm install -g pnpm
      - name: Install standard-version
        run: |
          pnpm install standard-version
      - name: Make sure the version in all code files is correct
        run: |
          pnpm run release -- --skip.commit --skip.tag --skip.changelog --release-as ${{ steps.get_semver.outputs.current_version }}
      - name: Commit code version changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          branch: noetic
          file_pattern: package.json ros_gazebo_gym_panda_example/package.xml
          commit_message: "chore(release): updates code version to ${{ steps.get_semver.outputs.current_version }}"
  create-release:
    # NOTE: Drafts a release for the new tag
    runs-on: ubuntu-latest
    needs: update-code-version
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          ref: noetic
          fetch-depth: 0
      - name: Get latest semver tag
        id: get_semver
        uses: rickstaa/action-get-semver@v1
        with:
          verbose: "true"
      - name: Build release changelog
        id: build_changelog
        uses: mikepenz/release-changelog-builder-action@main
        with:
          configuration: ".github/workflows/release_changelog_config.json"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Draft release
        uses: actions/create-release@v1
        with:
          tag_name: ${{ steps.get_semver.outputs.current_version }}
          release_name: ${{ steps.get_semver.outputs.current_version }}
          body: ${{ steps.build_changelog.outputs.changelog }}
          draft: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
